/* GENERATED by tools/make_hud2p.py -- DO NOT EDIT BY HAND.
   2-player compact HUD layout: panel size + BLOCK-RELATIVE field anchors,
   shared by the panel texture (src/hud2p_panel.h) and the core per-player
   widget draw (st_stuff.c:ST_DrawCompactWidgets).  Block origins: P1=(0,160),
   P2=(160,160).  Number anchors are RIGHT edges; % drawn at the number x. */
#ifndef HUD2P_LAYOUT_H
#define HUD2P_LAYOUT_H

#define HUD2P_W 160
#define HUD2P_H 64
#define HUD2P_ROW 32

#define HUD2P_AMMO_X  44  /* ready ammo right-edge (3 tall digits) */
#define HUD2P_AMMO_Y   3
#define HUD2P_HEALTH_X  90  /* health right-edge; % drawn at this x */
#define HUD2P_HEALTH_Y   3
#define HUD2P_ARMS_X 111  /* arms 2x3 grid (ST_ARMSX-rel: +12 x, +10 y per cell) */
#define HUD2P_ARMS_Y   4
#define HUD2P_CARDS_X 147  /* 3 key icons (7x5) stacked, +10 y each */
#define HUD2P_CARDS_Y   3
#define HUD2P_FACE_X   0  /* face top-left (block-rel ST_FACESX=143->0; V_DrawPatch adds STFST offset) */
#define HUD2P_FACE_Y  32
#define HUD2P_ARMOR_X  78  /* armor right-edge (% at this x) */
#define HUD2P_ARMOR_Y  35
#define HUD2P_AMMOCUR_X 131  /* per-weapon CURRENT ammo column right-edge (short nums) */
#define HUD2P_AMMOMAX_X 157  /* per-weapon MAX ammo column right-edge (short nums) */
#define HUD2P_AMMOROW0_Y  37  /* row 0 (BULL); pitch = 6px (rows at +0,+6,+12,+18) */

#endif /* HUD2P_LAYOUT_H */
