/* GENERATED by tools/make_hud4p.py -- DO NOT EDIT BY HAND.
   3/4-player compact HUD band: size + BLOCK-RELATIVE field anchors, shared by
   the band background (src/hud4p_panel.h) and the core per-player widget draw
   (st_stuff.c:ST_DrawQuadHud).  Band = bottom 16 px of each 160x112 quadrant;
   the 3D view above it is 160x96.  Number anchors are RIGHT edges. */
#ifndef HUD4P_LAYOUT_H
#define HUD4P_LAYOUT_H

#define HUD4P_W 160
#define HUD4P_H 16
#define HUD4P_QUAD_H 112  /* SCREENHEIGHT/2: quadrant height (view + band) */
#define HUD4P_KEYS_DX 9

#define HUD4P_AMMO_X  32  /* ready-weapon ammo right-edge (short nums; blank if no-ammo weapon) */
#define HUD4P_AMMO_Y   5
#define HUD4P_HEALTH_X  72  /* health right-edge; '%' drawn at this x */
#define HUD4P_HEALTH_Y   5
#define HUD4P_ARMOR_X 112  /* armor right-edge; '%' drawn at this x */
#define HUD4P_ARMOR_Y   5
#define HUD4P_KEYS_X 126  /* 1st key icon left-edge (7x5); + KEYS_DX per icon (co-op) */
#define HUD4P_KEYS_Y   5
#define HUD4P_FRAGS_X 152  /* deathmatch frag count right-edge (short nums) */
#define HUD4P_FRAGS_Y   5

#endif /* HUD4P_LAYOUT_H */
