/* GENERATED by tools/make_hud4p.py -- DO NOT EDIT BY HAND.
   3/4-player compact HUD band: size + anchors.  AM is flush-left (no %%, narrower),
   the armor %% is flush-right, HE is centred between.  AMMO_X/HEALTH_X/ARMOR_X are
   number RIGHT edges (all big red message font, right-justified in a 3-digit slot);
   the red '%%' is drawn AT HEALTH_X/ARMOR_X.  Labels are baked with a comfortable
   gap.  Keys/frags are a view OVERLAY at (ox + KEYS_X + i*KEYS_DX, oy - KEY_H). */
#ifndef HUD4P_LAYOUT_H
#define HUD4P_LAYOUT_H

#define HUD4P_W 160
#define HUD4P_H 16
#define HUD4P_QUAD_H 112  /* SCREENHEIGHT/2: quadrant height (view + band) */

#define HUD4P_AMMO_X   43  /* ammo digits RIGHT edge (big red, right-justified, no %) */
#define HUD4P_AMMO_Y   4
#define HUD4P_HEALTH_X  92  /* health digits RIGHT edge; red '%' at this x */
#define HUD4P_HEALTH_Y  4
#define HUD4P_ARMOR_X 149  /* armor digits RIGHT edge; red '%' at this x (flush right) */
#define HUD4P_ARMOR_Y  4

/* --- view overlay (keys / frags), relative to quadrant origin ox and band top oy --- */
#define HUD4P_KEY_H 7  /* overlay sits at oy - KEY_H (just above the band) */
#define HUD4P_KEYS_X 133  /* 1st key x-offset from ox (bottom-right of the view) */
#define HUD4P_KEYS_DX 9  /* upright STKEYS in a row (7w + 2px margin) */
#define HUD4P_FRAGS_X 158  /* deathmatch frag count RIGHT edge (x-offset from ox) */

#endif /* HUD4P_LAYOUT_H */
